### PR TITLE
Use 24-bits colors

### PR DESCRIPTION
**Pull request by ayosec**
Use 24 bits colors to render every pixel.

Here is a comparison between current (256 colors) code, and the new one  (16M colors).

compare

### CODE REVIEW

**Comment by hopey-dishwasher** [comment]
This looks great, but not all terminal emulators support 24-bit colours. 

Also, there's a lot more output, each escape code is longer, and there's an escape code for every 'pixel' now, whereas the existing implementation only prints the necessary escape codes when there's multiple consecutive pixels with the same colour. This probably doesn't matter most of the time, but if you're on some very slow ssh connection or something it might make a difference.

Rather than replacing the 240-colour version entirely, could we make 24-bit colour the default, and have a --low-colour option or something that falls back to the existing behaviour?

**Comment by hopey-dishwasher** [comment]
I thought that this would only be a problem for people using older or obscure terminals, but it appears that even gnome-terminal in ubuntu 14.04 doesn't support 24-bit colours escapes:
image

Is it possible to determine whether the current terminal supports it, and choose which method to use automatically?

**Comment by ayosec** [comment]
> Is it possible to determine whether the current terminal supports it, and choose which method to use automatically?

I'm not sure if this is possible, but I think that it is not =\

**Comment by hopey-dishwasher** [comment]
I made the original behaviour the default, and added a --true-colour option that uses the 24-bit colour. Also --true-color for folks that roll that way.

**Pull request merged**
